### ISSUE TITLE
USER STORY: Poll on Home Page

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/love-running#1]
In order to **hide the poll** as an **administrator**, I can **pick an expiry time for the poll when publishing**

## Acceptance Criteria
* The poll should disappear at 11.59pm on the selected date
* The expiry date should be at least 3 days after published

## Tasks
- [ ] update the poll design to include a date picker
- [ ] update the controller function
- [ ] write java script to allow for the poll to expire
- [ ] test functionality
