### ISSUE TITLE
USER STORY: Poll on Home Page

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/love-running#2]
In order to **provide anonymous feedback** as a **user**, I can **hide my identity when completing the poll**

## Acceptance Criteria
* Provide a checkbox to submit poll anonymously
* Checkbox should be preselected by default
* Should appear next to submit button

## Tasks 
- [ ] Add a checkbox with the label submit anonymously
- [ ] Add the selected attribute to the checkbox input class
- [ ] Create the checkbox to be inline with the submit button
- [ ] Create code to allow the anonymity feature
- [ ] Test functionality
